home_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.contrib import admin
from django.urls import path
from service import views

urlpatterns = [
    path('', views.index, name = 'home'),
    path('contact', views.contact, name = 'contact'),
    path('about', views.about, name = 'about'),
    path('career', views.career, name = 'career'),
    path('service_detail', views.service_detail,name='service_detail'),
    path('service_list', views.list_service,name='service_list'),
    path('service/<str:name>', views.service,name='service'),
    path('service/<str:service_name>/booking_confirm', views.mobile_otp_send, name="booking_confirm"),
    path('service/<str:service_name>/booking_completed', views.validate, name="booking_completed"),
    path('service/<str:service_name>/booking_completed/success', views.success, name="success"),
    path('create_career', views.create_career, name = 'create_career'),
    path('create_contact', views.create_contact_us, name = 'create_contact'),
    path('service/<str:service_name>/create_callback_request', views.create_callback_request, name = 'create_callback_request'),
]

app_name = 'service'

service/models.py
from django.db import models
from django.core.validators import RegexValidator

# Create your models here.

class City(models.Model):
    city_name = models.CharField(max_length=25,db_index=True, unique=True)
    pincode = models.PositiveIntegerField()
    state = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    slug = models.SlugField(max_length=200,db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        ordering = ('city_name',)
        
    def __str__(self):
        return self.city_name

class Service(models.Model):
    multiple_city = models.ManyToManyField(City)
    service_name = models.CharField(max_length=100) 
    image = models.ImageField(upload_to="images", blank=True)
    slug = models.SlugField(max_length=200,db_index=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    class Meta:
        ordering = ('created_at',)
        
    def __str__(self):
        return self.service_name


class ServiceType(models.Model): 
    service_name = models.ForeignKey(Service, related_name='service_type', on_delete=models.CASCADE)
    service_type = models.CharField(max_length=100) 
    image = models.ImageField(upload_to="images", blank=True)
    slug = models.SlugField(max_length=200,db_index=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    class Meta:
        ordering = ('service_type',)
        
    def __str__(self):
        return self.service_type

class ServiceCharge(models.Model):
    service_charge_name = models.ForeignKey(ServiceType, on_delete=models.CASCADE)   
    issue_type = models.CharField(max_length=200,blank=True, null= True)
    price = models.CharField(max_length=100, blank=False)   
    image = models.ImageField(upload_to="images", blank=True)
    slug = models.SlugField(max_length=200,db_index=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.issue_type

class BookAppointment(models.Model):
    client_name = models.CharField(max_length=100, blank=False)
    mobile = models.PositiveIntegerField(max_length =12, unique = True)
    email = models.EmailField()
    address = models.CharField(max_length=200, blank=False)
    landmark = models.CharField(max_length=200, blank=False)
    city = models.CharField(max_length=50)
    appointment_date = models.CharField(max_length=200, blank=False, null=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return self.client_name

class Contact(models.Model):
    name=models.CharField(max_length=256)
    email=models.EmailField(blank=True)
    phone=models.IntegerField(blank=True)
    body=models.TextField(blank=True)
    service_type=models.CharField(max_length=100, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class PhoneOTP(models.Model):
    phone_regex = RegexValidator( regex = r'^\+?1?\d{9,10}$', message ="Phone number must be entered in the format +919999999999. Up to 14 digits allowed.")
    phone       = models.CharField(validators =[phone_regex], max_length=17, unique = True)
    otp         = models.CharField(max_length=9, blank = True, null=True)
    count       = models.IntegerField(default=0, help_text = 'Number of otp_sent')
    validated   = models.BooleanField(default = False, help_text = 'If it is true, that means user have validate otp correctly in second API')
    otp_session_id = models.CharField(max_length=120, null=True, default = "")
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.phone) + ' is sent ' + str(self.otp) 

class CallbackRequest(models.Model):
    name=models.CharField(max_length=256)
    mobile=models.IntegerField(blank=True)
    body=models.TextField(blank=True)
    callback_timing =models.CharField(max_length=100, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Career(models.Model):
    name=models.CharField(max_length=256)
    mobile=models.IntegerField(blank=True)
    message=models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

service/views.py
from django.shortcuts import render, redirect
from service.models import Service, City, ServiceType, ServiceCharge, BookAppointment, PhoneOTP, Career, Contact, CallbackRequest
from math import ceil
from django.forms.models import model_to_dict

from django.db.models import Q
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib import messages
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
import http.client

import json
import requests
import ast
import random

conn = http.client.HTTPConnection("2factor.in")
api_key = "aac35574-3852-11eb-83d4-0200cd936042"
template_name = "A2Zhomeservice"

 
# Create your views here.
def index(request):
    all_city = City.objects.all()
    all_services= Service.objects.all()
    n = len(all_services)
    nSlides= n//4 + ceil((n/4) - (n//4))
    allservices=[[all_services, range(1, len(all_services)), nSlides],[all_services, range(1, len(all_services)), nSlides]]
    params={'cities':all_city,'range': range(nSlides), 'no_of_slides':nSlides,'allservices':allservices, 'services':all_services}
    return render(request,"index.html", params)
   

def list_service(request):
    list_services= Service.objects.all()
    n = len(list_services)
    query = request.GET.get("search")
    if query:
        list_services = list_services.filter(
            Q(service_name__icontains=query) |
            Q(city__icontains=query))
    nSlides= n//4 + ceil((n/4) - (n//4))
    params={'range': range(nSlides), 'no_of_slides':nSlides,'services':list_services, }
    return render(request,'list_service.html', params)   

def service_detail(request):
    if request.method =="POST":
        city_id =request.POST['city']
        service_name =request.POST['service']
        # service = Service.objects.get(multiple_city=city_id,service_name=service_name)
        # return render(request, 'service_detail.html',  {'service':service})   
        service_detail = Service.objects.get(service_name = service_name)
        service_type = ServiceType.objects.filter(service_name = service_detail.id)
        ser_type = []
        for stype in service_type:
            ser_type.append(stype.service_type)  
        serv_list = []
        dic_obj = {}
        for charge in service_type:
            service_name = charge.service_type
            service_charge= ServiceCharge.objects.filter(service_charge_name_id=charge.id)
            dic_obj[service_name] = service_charge
            serv_list.append(dic_obj)
        service_charge=[]
        for i in range(len(serv_list)):
            if serv_list[i] not in serv_list[i+1:]:
                service_charge.append(serv_list[i])
        return render(request, 'service.html',  {'service_detail':service_detail,'service_type':service_type,'service_charge':service_charge,'ser_type':ser_type})    


def service(request, name):
    service_detail = Service.objects.get(service_name = name)
    service_type = ServiceType.objects.filter(service_name = service_detail.id)
    ser_type = []
    for stype in service_type:
        ser_type.append(stype.service_type)  
    serv_list = []
    dic_obj = {}
    for charge in service_type:
        service_name = charge.service_type
        service_charge= ServiceCharge.objects.filter(service_charge_name_id=charge.id)
        dic_obj[service_name] = service_charge
        serv_list.append(dic_obj)
    service_charge=[]
    for i in range(len(serv_list)):
        if serv_list[i] not in serv_list[i+1:]:
            service_charge.append(serv_list[i])
    return render(request, 'service.html',  {'service_detail':service_detail,'service_type':service_type,'service_charge':service_charge,'ser_type':ser_type})    
    
    
def booking_confirm(request):
    return render(request,'confirm_booking.html', )  

def contact(request):
    return render(request,'contact.html', )

def about(request):
    return render(request,'about.html', )  

def career(request):
    return render(request,'career.html', )       

def success(request):
    return render(request,'success.html', )      


def mobile_otp_send(request, service_name):
    if request.method == 'POST':
        phone_number =request.POST.get('mobile')
        appointment_date = request.POST.get('date')
        requirement = request.POST.get('requirement')
        
        if phone_number:
            phone = str(phone_number)
            otp = send_otp(phone)
            if otp:
                old = PhoneOTP.objects.filter(phone__iexact = phone)
                if old.exists():
                    old = old.first()
                    count = old.count
                    if count > 5:
                        messages.error(request,  "Sending otp error. Limit Exceeded. Please Contact Customer support.")
                        return redirect('index.html')
                        
                    old.count = count +1
                    old.save()
                    url=f"https://2factor.in/API/V1/{api_key}/SMS/{phone_number}/{otp}/{template_name}"
                    conn.request("GET", url)
                    res = conn.getresponse()            
                    data = res.read()
                    data=data.decode("utf-8")
                    data=ast.literal_eval(data)
                    if data["Status"] == 'Success':
                        old.otp_session_id = data["Details"]
                        old.save()
                        print('In validate phone :'+old.otp_session_id)
                        messages.success(request,  "OTP sent successfully on your mobile.")
                        return render(request, 'confirm_booking.html',{'requirement':requirement,'phone_number':phone_number,'appointment_date':appointment_date})            
                    else:
                        messages.error(request, "Sending otp Failed.")
                        return HttpResponseRedirect('/')           
                else:
                    obj=PhoneOTP.objects.create(
                            phone=phone_number,
                            otp = otp,
                            )
                    url=f"https://2factor.in/API/V1/{api_key}/SMS/{phone_number}/{otp}/{template_name}"
                    conn.request("GET", url)
                    res = conn.getresponse()            
                    data = res.read()
                    data=data.decode("utf-8")
                    data=ast.literal_eval(data)

                    if data["Status"] == 'Success':
                        obj.otp_session_id = data["Details"]
                        obj.save()
                        print('In validate phone :'+obj.otp_session_id)
                        messages.success(request, "OTP sent successfully on your mobile.")
                        return render(request, 'confirm_booking.html', {'requirement':requirement,'phone_number':phone_number,'appointment_date':appointment_date} )  
                          
                    else:
                        messages.error(request, "Sending otp Failed.")
                        return redirect('') 
            else:
                messages.error(request,  "Sending otp error.")
                return redirect('') 
        else:
            messages.error(request,  "Phone number is not provided.")
            return HttpResponseRedirect('/')                  
    return HttpResponseRedirect('/')           

          
def send_otp(phone):
    if phone:
        key = random.randint(999,9999)
        print(key)
        return key
    else:
        return False          

def validate(request, *args, **kwargs):
    if request.method == 'POST':
        name = request.POST.get('name', False)
        email = request.POST.get('email', False)
        address = request.POST.get('address', False)
        landmark = request.POST.get('landmark', False)
        city = request.POST.get('city', False)
        appointment_date = request.POST.get('appointment_date', False)
        print(appointment_date)
        otp_sent = request.POST.get('otp', False)
        phone = request.POST.get('phone_number', False)
        description = request.POST.get('notes', False)
        print(description)
        if otp_sent:
            old = PhoneOTP.objects.filter(phone__iexact = phone)
            if old.exists():
                old = old.first()
                otp_session_id = old.otp_session_id
                validate_otp_url = f"https://2factor.in/API/V1/{api_key}/SMS/VERIFY/{otp_session_id}/{otp_sent}"
                
                conn.request("GET", validate_otp_url)
                res = conn.getresponse()    
                data = res.read()
                print(data.decode("utf-8"))
                data=data.decode("utf-8")
                data=ast.literal_eval(data)
                if data["Status"] == 'Success':
                    old.validated = True
                    old.save()
                    booking_obj=BookAppointment.objects.create(
                            client_name=name,
                            mobile = phone,
                            email = email,
                            address = address,
                            landmark = landmark,
                            appointment_date = appointment_date,
                            description = description
                            )
                    messages.success(request, "OTP MATCHED. Your booking order is confirmed.")
                    return render(request, 'success.html')

                else:
                    messages.error(request, "OTP Not MATCHED. Enter valid otp.")
                    return redirect('booking_confirm')
                    
            else:
                messages.error(request, "First Proceed via sending otp request.")
                return redirect('booking_confirm')
                          
        else:
            messages.error(request, "Please provide otp for Validation.")

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block container_block  %}

<h2> About Us </h2>

<div class="container-fluid">
  <h5>
 At A2zservice we offer several growth opportunities and platform to proove your 
 skills and work with one of the most dynamic team.
</h5>
<p> A2zservice is committed to provide professional home repair services to our consumers 
providing seamless experience of service delivery at doorstep, Currently we operate 
at Nagpur, Maharastra and soon planning to expand our operations in other ciites.
</p>
</div>


 {% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}


{% block container_block  %}

<!-- Masthead -->
   <header class="masthead text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">One Stop Home Services! <br> Let us do it for you </h1>
          <h3>Book your service online!  </h3>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          <form  action="{% url 'service:service_detail'  %}" method ="post"   enctype="multipart/form-data">
							{% csrf_token %} 
            <div class="form-row">
              <div class="col-12 col-md-4 mb-2 mb-md-0">
                   <select name = "service" class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                                    <option selected value="0"> Select Service</option>
                                    {% for service in services %}
									<option value="{{service.service_name}}">{{service.service_name}}</option>
                                    {% endfor %}
									
                             </select>
              </div>
              <div class="col-12 col-md-4 mb-2 mb-md-0">
                   <select name = 'city' class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                                    <option selected value="0"> Select City </option>
                                    {% for city in cities %}
									<option value="{{city.id}}">{{city.city_name}}</option>
                                    {% endfor %}
                             </select> 
              </div>
              <div class="col-12 col-md-3">
              
                <button type="submit" class="btn btn-block btn-md btn-info">Book Online</button>
              </div>
            </div>
          </form>
          <br>
       <div class="alert alert-light col-md-11 col-md-offset-4" role="alert">
          <a id="phone" href="tel:8210587612"><h4 class="alert-heading ">Call: 8210587612 </h4></a>
           <p>Phone Booking (8 AM to 8 PM) </p>
    </div>   

        </div>
      </div>
    </div>
  </header> 


  <!-- Icons Grid -->
  <section class="features-icons bg-light text-center">
    <div class="container">
     <h2> How it Works?</h2>
      <div class="row">
     
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
             <i class="icon-user m-auto text-primary"></i>
            </div>
            <h3>Select Service</h3>
            <p class="lead mb-0">Share your service requirement with us!</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-notebook m-auto text-primary"></i>
            </div>
            <h3>Book Appointment</h3>
            <p class="lead mb-0">Schedule a time for service delivery!</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="features-icons-item mx-auto mb-0 mb-lg-3">
            <div class="features-icons-icon d-flex">
              <i class="icon-check m-auto text-primary"></i>
            </div>
            <h3>Be Relax</h3>
            <p class="lead mb-0">Our Expert will fulfill service at your door step!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

<!-- crasoual-->

<div container>
<div class="container-xl">
	<div class="row">
		<div class="col-md-12">

    <h2>Trending <b>Services</b></h2>
<div id="myCarousel" class="carousel slide my-3" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                {% for i in range %}
				<li data-target="#myCarousel" data-slide-to="{{i}}" class="active"></li>
                {% endfor %}
	
			</ol>  

    <div class="carousel-inner ">
      <div class="carousel-item active">          
        {% for i in services|slice:"0:"%}
        <div class="col-xs-3 col-sm-3 col-md-3">
         <div class="thumb-wrapper">
        
           <span class="wish-icon"><i class="fa fa-heart-o"></i></span> 
				<div class="img-box">
				<a href = "{% url 'service:service' name=i.service_name%}">	<img src="{{i.image.url}}" class="img-fluid " alt=""></a>								
				</div>
            
            <div class="thumb-content">
			<h4>{{i.service_name|truncatechars_html:15}}</h4>									
			<div class="star-rating">
			    <ul class="list-inline">
			        <li class="list-inline-item"><i class="fa fa-star"></i></li>
					<li class="list-inline-item"><i class="fa fa-star"></i></li>
					<li class="list-inline-item"><i class="fa fa-star"></i></li>
					<li class="list-inline-item"><i class="fa fa-star"></i></li>
					<li class="list-inline-item"><i class="fa fa-star-o"></i></li>
				</ul>
			</div>	
            {% comment %} <p class="item-price"> <b>{{i.city}}</b></p> {% endcomment %}
			
			<a href="{% url 'service:service' name=i.service_name%}" class="btn btn-primary">Book Online</a>
			</div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}
        {% endfor %}
    </div>
   </div>
  </div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>
  </div>
  </div>
 </div>
<!-- crasoual end-->


  <!-- Testimonials -->
  <section class="testimonials text-center bg-light">
    <div class="container">
      <h2 class="mb-5">What people are saying...</h2>
      <div class="row">
        <div class="col-lg-4">
          <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="static/img/testimonials-1.jpg" alt="">
            <h5>Margaret E.</h5>
            <p class="font-weight-light mb-0">"This is fantastic! Thanks so much guys!"</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="static/img/testimonials-2.jpg" alt="">
            <h5>Fred S.</h5>
            <p class="font-weight-light mb-0">"Recommended it to anyone looking for a good service . Great Service at an Affordable Price."</p>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="testimonial-item mx-auto mb-5 mb-lg-0">
            <img class="img-fluid rounded-circle mb-3" src="static/img/testimonials-3.jpg" alt="">
            <h5>Sarah W.</h5>
            <p class="font-weight-light mb-0">"Thanks so much for making these free resources available to us!"</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Call to Action -->
  <section class="call-to-action text-white text-center">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-4">For any query please contact us!</h1>
        </div>
        <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
          
    <form method="post" action="contactus">
    {% csrf_token %}
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputName">Name</label>
      <input type="text" class="form-control" placeholder="Enter your name...">
    </div>
    <div class="form-group col-md-6">
      <label for="inputMobile">Mobile</label>
      <input type="text" class="form-control"  placeholder="Enter your mobile no...">
    </div>
  </div>
<div class="form-group">
    <label for="inputAddress">Message</label>
    <input type="text" class="form-control" id="inputdescription" placeholder="Enter Message here..">
  </div>  
  <button type="submit" class="btn btn-info"><i class="fa fa-paper-plane"></i> Send !</button>
</form>

        </div>
      </div>
    </div>
  </section>


 {% endblock  %}

templates/list_service.html
{% extends 'base.html' %}
{% load static %}

{% block container_block  %}
<!-- Masthead -->
   <header class="box1 text-white text-center">
    <div class="overlay"></div>
    <div class = "box1">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">List of Services</h1>
          <h3><i class="fa fa-check-square-o"></i> Checked Expert Technician
          <i class="fa fa-check-square-o"></i> Free Inspection
          <i class="fa fa-check-square-o"></i> 7 days warranty. </h3>
        </div>
      </div>
    </div>
    </div>
  </header> 
<br>

{% comment %} <div class="container">
     <h2>Choose your service </h2>
            <div class="row">
           
            {% for service in services%}

        <div class="col-md-3">
        <div class="dress-card">
          <div class="dress-card-head">
            <a href = "{% url 'service:service' name=service.service_name%}"> <img class="dress-card-img-top" src="{{service.image.url}}" alt=""> </a>
            <div class="surprise-bubble"><span class="dress-card-heart">
                <i class="fas fa-heart"></i>
              </span><a href="{% url 'service:service' name=service.service_name%}"> <span>More</span></a></div>
          </div>
          <div class="dress-card-body">
            <h4 class="dress-card-title"><a href="{% url 'service:service' name=service.service_name%}" >{{service.service_name}}</a></h4>
            <p class="dress-card-para">{{service.description|truncatechars_html:15}}</p>
            
            <div class="row">
              <div class=" card-button"><a href="{% url 'service:service' name=service.service_name%}"><div class="card-button-inner bag-button">Book service</div></a></div>
             
            </div>
          </div>
        </div>
      </div>
        
            {% endfor %} 

                

        </div>
    </div> {% endcomment %}



<!-- crasoual-->

<div container>
<div class="container-xl">
	<div class="row">
		<div class="col-md-12">

    <h2>Coose Your <b>Services</b></h2>
<div id="myCarousel" class="carousel slide my-3" data-ride="carousel" data-interval="5000">
            <ol class="carousel-indicators">
                {% for i in range %}
				<li data-target="#myCarousel" data-slide-to="{{i}}" class="active"></li>
                {% endfor %}
	
			</ol>  

    <div class="carousel-inner ">
      <div class="carousel-item active">          
        {% for service in services|slice:"0:"%}
        <div class="col-md-3">
        <div class="dress-card">
          <div class="dress-card-head">
            <a href = "{% url 'service:service' name=service.service_name%}"> <img class="dress-card-img-top" src="{{service.image.url}}" alt=""> </a>
            <div class="surprise-bubble"><span class="dress-card-heart">
                <i class="fas fa-heart"></i>
              </span><a href="{% url 'service:service' name=service.service_name%}"> <span>More</span></a></div>
          </div>
          <div class="dress-card-body">
            <h4 class="dress-card-title"><a href="{% url 'service:service' name=service.service_name%}" >{{service.service_name}}</a></h4>
            <p class="dress-card-para">{{service.description|truncatechars_html:15}}</p>
            
            <div class="row">
              <div class=" card-button"><a href="{% url 'service:service' name=service.service_name%}"><div class="card-button-inner bag-button">Book service</div></a></div>
             
            </div>
          </div>
        </div>
      </div>
        {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last %}
      </div><div class="carousel-item">
        {% endif %}
        {% endfor %}
    </div>
   </div>
  </div>
    <!-- left and right controls for the slide -->
    <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" data-slide="next">
        <span class="carousel-control-next-icon"></span>
    </a>
</div>
  </div>
  </div>
 </div>
<!-- crasoual end-->    


{% endblock %}

templates/messages.html
{% if messages  %}
  {% for msg in messages%}
   <div class="alert {{msg.tags}} m-2" id="msg" role="alert"> 
      {{msg}}
     </div>
  {% endfor %}

{% endif %}

templates/service_detail.html
{% extends 'base.html' %}
{% load static %}

{% block container_block  %}
<br>
{{service.service_name}}

<br>

<div class="tch-img">
                    
 <img class="card-img-top" src={{ service.image.url }} class="img-responsive" alt="" width="750px" height="420px">
						
</div>
<br>
{% endblock %}

templates/success.html
{% extends 'base.html' %}

{% load static %}


{% block container_block  %}

<!-- Masthead -->
   <header class="box text-white text-center">
    <div class="overlay"></div>
    <div class = "box">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <h1 class="mb-5">Thank You for booking appointment </h1>

        </div>
      </div>
    </div>
    </div>
  </header> 
 
 <div class="alert alert-success" role="alert">
 <h2> Awesome!</h2>
  <h4 style={text-align: center;}><strong> You have successfully booked appointment with us</strong></h4>
     <h4 style={text-align: center;}>Our support member will contact you soon </h4>
</div>

 {% endblock %}